services:
  - type: web
    name: mine-app-server
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run start:clustered
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: MAX_WORKERS
        value: "8"
      - key: LOG_LEVEL
        value: "info"
    healthCheckPath: /health
    autoDeploy: true
    branch: main 